spring:
  datasource:
    url: jdbc:mysql://localhost:3306/code_review_db
    username: root
    password: 'raj@patel@23'
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

  mail:
    host: smtp.gmail.com
    port: 587
    username: smartattendanceprojectteam@gmail.com
    password: fyhbnkrhgwpceuin
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        debug: false

  security:                        # ← 2 spaces indent under spring
    oauth2:
      client:
        registration:

          google:
            client-id: 766656698734-31frh31tfr9sgn12igvlhbvu3p958hsl.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "http://localhost:8080/oauth2/callback/google"
            scope:
              - email
              - profile

          github:
            client-id: Ov23liUxzT5OUh9VHjzr
            client-secret: 10e96e59ca12b4518bf9a0c8d7d639bd431e93bb
            redirect-uri: "http://localhost:8080/oauth2/callback/github"
            scope:
              - user:email
              - read:user

        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id

app:
  jwt:
    secret: 7fd92bc0cbe4b9fbc4f93f5a0e73fef9cbe2f9f0b4a5f2f0cbb912345678abcd
    access-token-expiration-ms: 900000
    refresh-token-expiration-ms: 604800000

  otp:
    expiry-minutes: 10

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
    com.capstoneproject: DEBUG